name: Format and Fix
on:
  pull_request:
    branches: [main, master]
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git fetch origin master && git checkout -b master origin/master && git checkout -
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - id: check
      continue-on-error: true
      run: dotnet format whitespace --verify-no-changes ModSync.sln --include $(git diff --name-only HEAD origin/master | tr '\n' ' ')
    - if: steps.check.outcome == 'failure'
      run: dotnet format whitespace ModSync.sln --include $(git diff --name-only HEAD origin/master | tr '\n' ' ')
    - if: steps.check.outcome == 'failure'
      run: |
        git config user.name "bot"
        git config user.email "bot@example.com"
        git commit -am "Auto-fix formatting"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}